#!/usr/bin/env python3
"""Spatial Block CV + RF + XGBoost baseline"""
import pandas as pd, numpy as np, json, csv, time, os
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score

from config import TRAIN_CSV, RESULTS_DIR

OUTDIR = RESULTS_DIR
os.makedirs(OUTDIR, exist_ok=True)

# Load the pre-built training data WITH coordinates (generated by data prep or previous run of this)
df = pd.read_csv(TRAIN_CSV)
# Dynamically determine environmental columns (exclude label, fold, coords)
non_env = ['label', 'fold', 'decimalLatitude', 'decimalLongitude']
env_cols = [c for c in df.columns if c not in non_env]
df = df[env_cols + ['decimalLatitude', 'decimalLongitude', 'label', 'fold']].copy()
print(f"✅ Loaded training with coords ({len(env_cols)} env vars): {len(df):,} (P={(df['label']==1).sum():,})")
print(f"   Env cols: {env_cols}")

# ====== Spatial Block CV (external blockCV folds) ======
n_folds = len(np.unique(df['fold']))
fold_ids = df['fold'].values

print(f"\nSpatial blocks (blockCV 150km external folds, k={n_folds}):")
for f in range(n_folds):
    mask = fold_ids == f
    n_p = ((mask) & (df["label"] == 1)).sum()
    n_bg = ((mask) & (df["label"] == 0)).sum()
    print(f"  Fold {f}: {mask.sum():,} samples (P={n_p}, BG={n_bg})")

# ====== Prepare features ======
X = df[env_cols].values
y = df["label"].values
X = StandardScaler().fit_transform(X)

# ====== Run RF + XGBoost with spatial CV (checkerboard) ======
def spatial_cv_eval(model_fn, model_name):
    aucs = []
    preds = np.zeros(len(y))
    for f in range(n_folds):
        te = fold_ids == f
        tr = ~te
        if te.sum() == 0 or tr.sum() == 0:
            continue
        m = model_fn()
        m.fit(X[tr], y[tr])
        prob = m.predict_proba(X[te])[:, 1]
        preds[te] = prob
        auc = roc_auc_score(y[te], prob)
        aucs.append(auc)
        print(f"  {model_name} fold {f}: AUC={auc:.4f}")
    
    # Save to _cb to match other baselines
    mdir = f"{OUTDIR}/{model_name}_cb"
    os.makedirs(mdir, exist_ok=True)
    with open(f"{mdir}/metrics.json", "w") as f:
        json.dump({
            "model": model_name,
            "cv": "blockCV 150km external folds",
            "auc_mean": round(np.mean(aucs), 4),
            "auc_std": round(np.std(aucs), 4),
            "folds": [round(a, 4) for a in aucs]
        }, f, indent=2)
    
    pd.DataFrame({"label": y, "pred_prob": preds}).to_csv(f"{mdir}/predictions.csv", index=False)
    return np.mean(aucs), np.std(aucs)

t0 = time.time()
print(f"\n=== Random Forest ===")
rf_auc, rf_std = spatial_cv_eval(lambda: RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42, n_jobs=-1), "rf")
print(f"\n=== XGBoost ===")
xgb_auc, xgb_std = spatial_cv_eval(lambda: XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.1, random_state=42, verbosity=0), "xgb")

print(f"\n{'='*50}")
print(f"📊 blockCV 150km external folds Results:")
print(f"  Random Forest:   AUC={rf_auc:.4f} ± {rf_std:.4f}")
print(f"  XGBoost:         AUC={xgb_auc:.4f} ± {xgb_std:.4f}")
print(f"  ⏱ {time.time()-t0:.1f}s")
